### ISSUE TITLE
デプロイ先の選定

### ISSUE THREAD

**Issue by hacusk** [frontend-conference-hokkaido-2024/landing-page-2024#25]
## 目的
このLPのデプロイ先を選定する。
可能であれば無料でホストできるかつ、任意団体でも使って良いやつを選出したい。

以下案
- Vercel
- Cloudflare
- S3

## なぜ必要か
ホスティングしないとLPを公開できないため。

## ゴール
選出し、@yud0uhu さんにアカウントを取得してもらう。

**Comment by hacusk** [comment]
## Vercel
### メリット
- Nextjsとの相性が良い
### デメリット
- CI/CDを組むのがめんどそう（これは俺の偏見）

## Cloudflare
### メリット
- DNSと適当に組み合わせれる
- GitHubActionsとの組み合わせが楽
### デメリット
- 無料で使えるか？

## S3
### メリット
- とりあえずビルドしたやつをぶん投げるだけで公開できる
### デメリット
- お金がかかる

**Comment by yud0uhu** [comment]
ドメインは[Cloudflare Register](https://www.cloudflare.com/ja-jp/products/registrar/) で買おうと思ってます（お安いので）
* 参考：年間$9.77（24/4/27現在 1,544.59 円）

SSGにして、Cloudflareを噛ませてSSL化してGitHub Pagesでも十分そうかな？とも思いました！

**参考URL**
https://rcmdnk.com/blog/2017/01/03/blog-github-web/
https://docs.github.com/ja/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

# メリット
* GitHub Actionsが使えるのでCI/CDが組みやすそう
* 無料
* 広告も貼れるらしい

# デメリット
* 商用利用は不可（非営利目的の任意団体は可なのか？が懸念ですが...）
* プライベートリポジトリだと使えないですが、publicなので問題なさそう

# 制約・規約などなど
制約系
> 公開されたGitHub Pagesのサイトは1GB以上であってはなりません。
> GitHub Pages のデプロイは、10 分を超えるとタイムアウトになります。
> GitHub Pages サイトには、月当たり 100 GB の ソフトな 帯域幅制限があります。
> GitHub Pages サイトには、1 時間あたり 10 ビルドの "ソフト" 制限があります。__ カスタム GitHub Actions ワークフローでサイトをビルドして公開する場合、この制限は適用されません

**参考URL**
https://docs.github.com/ja/pages/getting-started-with-github-pages/about-github-pages#usage-limits

規約系
> GitHub Pages は、オンライン ビジネス、eコマース サイト、主に商取引の円滑化またはサービスとしての商用ソフトウェア (SaaS) の提供のどちらかを目的とする、その他の Web サイトを運営するための無料の Web ホスティング サービスとしての使用を意図したものではなく、またそのような使用を許可するものでもありません。 GitHub Pages サイトは、パスワードやクレジットカード番号といった機密情報のやりとりに使うべきではありません。

さらに、GitHub Pages の使用には、一獲千金を狙った計画、わいせつなコンテンツ、暴力的あるいは脅迫的なコンテンツや活動に関する制限など、[GitHub 利用規約](https://docs.github.com/ja/site-policy/github-terms/github-terms-of-service)が適用されます。

https://docs.github.com/ja/pages/getting-started-with-github-pages/about-github-pages#github-pages%E3%81%AE%E5%88%A9%E7%94%A8%E4%B8%8A%E3%81%AE%E5%88%B6%E9%99%90

**Comment by yud0uhu** [comment]
Vercelについて

* Hobbyプランの利用は非営利の個人使用のみであること
* 商用利用の定義については以下の記載があり、HobbyプランだとジョブボードがNGかもという懸念があります

> The inclusion of advertisements, including but not limited to online advertising platforms like Google AdSense
[Fair Use Policy – Vercel Docs](https://vercel.com/docs/concepts/limits/fair-use-policy#commercial-usage)

Google AdSenseのようなオンライン広告プラットフォームを含むがこれに限定されない広告を含めること。

https://vercel.com/docs/limits/fair-use-guidelines#commercial-usage

**Comment by 618knot** [comment]
所感メモ
GitHub PagesかCloudflareの二択

- GitHub Pages
  - 規約的問題がクリアできるならこっちでよさそう
- Cloudflare
  - 前例があるので安心
  - GitHub Pagesが怪しいのであればこっちでいい

**Comment by hacusk** [comment]
GitHub PagesでもOKそうなので、一旦その前提で進めていきますか。

@yud0uhu @618knot 
確認ありがとうございます:bow:
