### ISSUE TITLE
 EventOverView の修正 

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#76]
- タイトルロゴ
- 会場名

![スクリーンショット 2024-05-19 23 28 04](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/1ff932e0-7fe1-45be-886d-389b195b3095)

タイトル部分は画像を書き出しで対応する

**Comment by 618knot** [comment]
すでに#14 で実装済みの`EventOverView`コンポーネントについて、下記の対応をする
- フロントエンドカンファレンス北海道2024(文字列) -> Frontend Conference HOKKAIDO(画像) に差し替え
- 開催日時をを画像通りに修正
- 開催時間を削除
- 会場名を修正
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/d7f26126-5fff-4b8d-8ee0-3ddebeb06b98)
