### ISSUE TITLE
チケット購入ボタンの実装 

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#77]
チケット購入ボタン, 注意書き

![スクリーンショット 2024-05-19 23 29 29](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/661ca491-f869-4407-88b1-510e4012997a)

**Comment by 618knot** [comment]
アイコン・ボタン名・注釈は一か所だけ違う場所があるので、デフォルト値として設定しておいて呼び出すときにも設定できるようにしておく

**Comment by WataruNishimura** [comment]
#95 を先に着手

**Comment by 618knot** [comment]
チケット購入ボタンと及びその注釈は、複数個所で使用される。
そのため#95 で実装される共通ボタンコンポーネントを使用して、チケット購入ボタンを実装しておく。
