### ISSUE TITLE
【最優先】タイトルコンポーネントの作成

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#78]
タイトル部分は共通なので、取り回ししやすいコンポーネントを作成する

↓該当部分

![スクリーンショット 2024-05-19 23 30 13](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/be0fa114-3c69-4398-aaa9-d5ee90a96dc3)

![スクリーンショット 2024-05-19 23 31 23](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/2b6fbc10-2188-4a2d-bae2-5b607256486c)

![スクリーンショット 2024-05-19 23 31 36](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/cb2cff93-08de-4cbd-ac9c-4c401f79adf1)

**Comment by WataruNishimura** [comment]
テキストスタイルは共通なのでtailwind.config.tsに記述してください.
