### ISSUE TITLE
【最優先】画像を登録

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#79]
以下も画像として書き出す想定。
忘れない。

![スクリーンショット 2024-05-19 23 32 54](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/0dc5f174-0efb-4398-b608-b2339912cf61)

**Comment by 618knot** [comment]
デザインの一新によってタイトルをはじめとして、様々な場所で複数種類のアイコン(イラスト)が設置されるようになる。
始めにこれらを追加しておかないと進まないので、ここでまとめて追加する。
