### ISSUE TITLE
EventSummaryの修正

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#80]
新規デザインに合わせて既存のコンポーネントを調整する
チケット購入ボタンの実装が完了している必要あり (https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/issues/95)

![スクリーンショット 2024-05-19 23 35 56](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/88b5ec0e-6ba1-4fcc-b92f-7817f556c75b)

**Comment by 618knot** [comment]
todo
- タイトルを修正
- タイトル下の画像を差し替え・位置調整
- 余分な説明文の削除
- チケット購入ボタンを追加
- 既存のフォロー・シェアボタンを共通ボタンに差し替え
