### ISSUE TITLE
AccessInfo の修正

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#81]
![スクリーンショット 2024-05-19 23 37 12](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/e603326a-1ffe-46be-95c1-4ffaf0acbdfd)

**Comment by 618knot** [comment]
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/16
で実装した`AccessInfo`コンポーネントをデザインの変更に合わせて守勢する。
todo
- タイトルの修正
- 埋め込みの角を丸める
  - tabキーでフォーカスorスマホで触ろうとすると、フォーカスが出てきて変な感じになるので注意
- 会場・所在地・最寄駅項目をブロックとして背景を付ける

**Comment by 618knot** [comment]
既存の実装で`AccessInfo`と同じ場所に`オンライン`項目も実装されている。
これは#82にて分離される。
