### ISSUE TITLE
スタッフブログコンポーネントを作成

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#84]
共通ボタンコンポーネントの実装が完了している必要あり (https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/issues/95)

![スクリーンショット 2024-05-19 23 42 29](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/9ccfe11a-8dfc-46e1-8de6-920fb3812956)

**Comment by 618knot** [comment]
https://note.com/api/v2/creators/fec_hokkaido/contents?kind=note&page=1
note APIのエンドポイント
