### ISSUE TITLE
ジョブコンポーネント作成

### ISSUE THREAD

**Issue by ebibibibibi** [frontend-conference-hokkaido-2024/landing-page-2024#91]
ジョブボード (https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/issues/92) 内に配置するコンポーネントを作成する。

![スクリーンショット 2024-05-20 0 03 57](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/91860481/4dc854f1-9f9c-4808-8857-1e1c9a07a141)

**Comment by 618knot** [comment]
#18

**Comment by ebibibibibi** [comment]
かぶってますね。。失礼しました。こちらクローズします。
